// TRANSACTION ACTIONS
export const TRANSACTION_ADD_TRANSACTION = "TRANSACTION_ADD_TRANSACTION";
export const TRANSACTION_UPDATE_LATEST_TRANSACTIONS = "TRANSACTION_UPDATE_LATEST_TRANSACTIONS";
export const TRANSACTION_UPDATE_TRANSACTIONS_FILTER_BY_DATE = "TRANSACTION_UPDATE_TRANSACTIONS_FILTER_BY_DATE";
export const TRANSACTION_API_CALL_STARTED = "TRANSACTION_API_CALL_STARTED";
export const TRANSACTION_API_CALL_COMPLETED = "TRANSACTION_API_CALL_COMPLETED";
export const TRANSACTION_API_CALL_ERROR = "TRANSACTION_API_CALL_ERROR";
export const TRANSACTION_API_CALL_RESET = 'TRANSACTION_API_CALL_RESET';
// CATEGORY ACTIONS
export const CATEGORY_UPDATE_CATEGORIES = "CATEGORY_UPDATE_CATEGORIES";
export const CATEGORY_API_CALL_STARTED = "CATEGORY_API_CALL_STARTED";
export const CATEGORY_API_CALL_COMPLETED = "CATEGORY_API_CALL_COMPLETED";
export const CATEGORY_API_CALL_ERROR = "CATEGORY_API_CALL_ERROR;"
// ACCOUNT ACTIONS
export const ACCOUNT_UPDATE_ACCOUNTS = "ACCOUNT_UPDATE_ACCOUNTS";
export const ACCOUNT_API_CALL_STARTED = "ACCOUNT_API_CALL_STARTED";
export const ACCOUNT_API_CALL_COMPLETED = "ACCOUNT_API_CALL_COMPLETED";
export const ACCOUNT_API_CALL_ERROR = "ACCOUNT_API_CALL_ERROR;"
export const ACCOUNT_ADD_ACCOUNT = "ACCOUNT_ADD_ACCOUNT";
export const ACCOUNT_API_CALL_RESET= "ACCOUNT_API_CALL_RESET";
// USER ACTIONS
export const USER_CREATED = "USER_CREATED";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_API_CALL_STARTED = "USER_API_CALL_STARTED";
export const USER_API_CALL_COMPLETED = "USER_API_CALL_COMPLETED";
export const USER_API_CALL_ERROR = "USER_API_CALL_ERROR;"
// CURRENCY ACTIONS
export const CURRENCY_UPDATE_CURRENCIES = "CURRENCY_UPDATE_CURRENCIES";
export const CURRENCY_API_CALL_STARTED = "CURRENCY_API_CALL_STARTED";
export const CURRENCY_API_CALL_COMPLETED = "CURRENCY_API_CALL_COMPLETED";
export const CURRENCY_API_CALL_ERROR = "CURRENCY_API_CALL_ERROR;"
// ACCOUNT TYPE ACTIONS
export const ACCOUNT_TYPE_UPDATE_ACCOUNT_TYPES = "ACCOUNT_TYPE_UPDATE_ACCOUNT_TYPES";
export const ACCOUNT_TYPE_API_CALL_STARTED = "ACCOUNT_TYPE_API_CALL_STARTED";
export const ACCOUNT_TYPE_API_CALL_COMPLETED = "ACCOUNT_TYPE_API_CALL_COMPLETED";
export const ACCOUNT_TYPE_API_CALL_ERROR = "ACCOUNT_TYPE_API_CALL_ERROR;"