// TRANSACTION ACTIONS
export const TRANSACTION_UPDATE_LATEST_TRANSACTIONS = "TRANSACTION_UPDATE_LATEST_TRANSACTIONS";
export const TRANSACTION_UPDATE_TRANSACTIONS_FILTER_BY_DATE = "TRANSACTION_UPDATE_TRANSACTIONS_FILTER_BY_DATE";
export const TRANSACTION_API_CALL_STARTED = "TRANSACTION_API_CALL_STARTED";
export const TRANSACTION_API_CALL_COMPLETED = "TRANSACTION_API_CALL_COMPLETED";
export const TRANSACTION_API_CALL_ERROR = "TRANSACTION_API_CALL_ERROR;"
// CATEGORY ACTIONS
export const CATEGORY_UPDATE_CATEGORIES = "CATEGORY_UPDATE_CATEGORIES";
export const CATEGORY_API_CALL_STARTED = "CATEGORY_API_CALL_STARTED";
export const CATEGORY_API_CALL_COMPLETED = "CATEGORY_API_CALL_COMPLETED";
export const CATEGORY_API_CALL_ERROR = "CATEGORY_API_CALL_ERROR;"
// ACCOUNT ACTIONS
export const ACCOUNT_UPDATE_ACCOUNTS = "ACCOUNT_UPDATE_ACCOUNTS";
export const ACCOUNT_API_CALL_STARTED = "ACCOUNT_API_CALL_STARTED";
export const ACCOUNT_API_CALL_COMPLETED = "ACCOUNT_API_CALL_COMPLETED";
export const ACCOUNT_API_CALL_ERROR = "ACCOUNT_API_CALL_ERROR;"