# BUILD
# docker build -t budget_frontend:<tag> -f DockerFile .
# RUN
# docker run -p 80:80 -d budget_frontend:<tag>

FROM node:14.18.1 as compilacion

COPY . /opt/app

WORKDIR /opt/app

RUN npm install

RUN npm run build

FROM nginx:1.21.3

COPY --from=compilacion /opt/app/build /usr/share/nginx/html